### ISSUE TITLE
New version of Cairo2

### ISSUE THREAD

**Issue by Chris00** [jacquev6/JsOfOCairo#1]
If you want to stay compatible with *cairo2*, it will soon acquire new modules: `Ft` and `Cairo_pango`.  I also removed many labels when they did not represent a strong advantage because the default configuration of *Dune* is to require them and, as many users may not want/know to turn the warning off, the code may quickly become heavy (for no benefit).

**Comment by jacquev6** [comment]
Thank you for letting me know! I'll look deeper into that when I have time.
